collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.6384744
color:
  saturation: 0.1034307
  brandStrength: 0.03226184
  rhythmicContrast: 0.005735083
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.8394838
layout_spectrum: 0.9928315
name: Gaudi
