name: Gaudi
favicon: null
layout_spectrum: 0.9928315
typography_spectrum: 0.1774193
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Gaudi Clique
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.03226184
  lightness: 0.8394838
  saturation: 0.1034307
  rhythmicContrast: 0.005735083
purpose: []
